SELECT * FROM tabla WHERE fecha -- FECHA DE MAÑANA
			BETWEEN (CURDATE()) AND ADDDATE(CURDATE(), INTERVAL 1 DAY); 

SELECT * FROM tabla WHERE fecha -- FECHA AYER
			BETWEEN SUBDATE(CURDATE(), INTERVAL 1 DAY) AND (CURDATE()); 
			
			
SELECT * FROM tabla WHERE fecha -- HACE UNA SEMANA
			BETWEEN SUBDATE(CURDATE(), INTERVAL 8 DAY) AND (CURDATE()); 
			

select *from ventas_venta where fecha_venta BETWEEN (CURDATE()) AND ADDDATE(CURDATE(), INTERVAL 1 DAY);
